### PR TITLE
Added Barrel & Shulker Box as a container

### PR DESCRIPTION
**Pull request by ElBananaa**

### CODE REVIEW

**Comment by ElBananaa** [comment]
I wanted to add all the shulkers at first, but since there's 15 different shulker, I wasn't sure about adding them all tho.

**Comment by OmerBenGera** [comment]
> 
> 
> I wanted to add all the shulkers at first, but since there's 15 different shulker, I wasn't sure about adding them all.

In versions that barrels or shulkers don't exist, it will cause issues.
Instead, use getType#name and compare strings for these materials.
About shulkers - instead of checking if the Material's name equals to "SHULKER_BOX", check if it contains the sequence

**Comment by ElBananaa** [comment]
> > I wanted to add all the shulkers at first, but since there's 15 different shulker, I wasn't sure about adding them all.
> 
> In versions that barrels or shulkers don't exist, it will cause issues.
> Instead, use getType#name and compare strings for these materials.
> About shulkers - instead of checking if the Material's name equals to "SHULKER_BOX", check if it contains the sequence

I'm beginning in java, so it might sound stupid, but for some reasons, I can't check for its state?

**Comment by OmerBenGera** [comment]
> > > I wanted to add all the shulkers at first, but since there's 15 different shulker, I wasn't sure about adding them all.
> > 
> > 
> > In versions that barrels or shulkers don't exist, it will cause issues.
> > Instead, use getType#name and compare strings for these materials.
> > About shulkers - instead of checking if the Material's name equals to "SHULKER_BOX", check if it contains the sequence
> 
> I'm begenning with java and I never worked with NMS, but if I'm not wrong, checking if NMSAdapter isn't legacy should work there. Also, for some reasons, neither the Shulker_box nor the barrel are found when checking for the material.
> 
> Instead of checking if it contains "SHULKER_BOX", why don't I simply check for its state?

I dont understand how the NMSAdapter has anything to do with that.

**Comment by OmerBenGera** [comment]
Also, you cant check if the block state is a ShulkerBox, as in 1.8 there's no such thing as ShulkerBox, and it will throw errors.

**Comment by ElBananaa** [comment]
> > > > I wanted to add all the shulkers at first, but since there's 15 different shulker, I wasn't sure about adding them all.
> > > 
> > > 
> > > In versions that barrels or shulkers don't exist, it will cause issues.
> > > Instead, use getType#name and compare strings for these materials.
> > > About shulkers - instead of checking if the Material's name equals to "SHULKER_BOX", check if it contains the sequence
> > 
> > 
> > I'm begenning with java and I never worked with NMS, but if I'm not wrong, checking if NMSAdapter isn't legacy should work there. Also, for some reasons, neither the Shulker_box nor the barrel are found when checking for the material.
> > Instead of checking if it contains "SHULKER_BOX", why don't I simply check for its state?
> 
> I dont understand how the NMSAdapter has anything to do with that.

Well, unlike shulker boxes, barrels don't exist in previous versions, so I don't really know how I could do then.

> Also, you cant check if the block state is a ShulkerBox, as in 1.8 there's no such thing as ShulkerBox, and it will throw errors.

Didn't think of versions older than 1.12 yeah, also just noticed that while looking at spigot api.

**Review by OmerBenGera — CHANGES_REQUESTED** [review]
Should be changed to Material#name to check for barrels and shulker boxes, otherwise in 1.8 there will be errors

**Comment by OmerBenGera** [comment]
I am closing this, as I added the support for these containers.
Next time, please build out of dev and not master, and make the changes I request.

**Comment by ElBananaa** [comment]
Hey!
Thanks, and sorry, I completely lost the track of this.
Well, yeah, next time I'll build from dev, if I can (For some reasons, intellij didn't want to work properly with the plugin) ^^

**Comment by OmerBenGera** [comment]
> 
> 
> Hey!
> Thanks, and sorry, I completely lost the track of this.
> Well, yeah, next time I'll build from dev, if I can (For some reasons, intellij didn't want to work properly with the plugin) ^^

You can switch branches in Intellij and then work on the branch you want :)
If you need help with that, ask me on discord for help

**Pull request closed without merging**
